DSCH 2.6h
VERSION 3/9/2003 5:03:12 PM
BB(60,5,80,25)
SYM  #dgmos
BB(60,5,80,25)
TITLE 75 20  #dgmos
MODEL 905
PROP   2.0 0.25                                                                                                                                                                                                       
REC(61,10,19,15,r)
VIS 0
PIN(80,25,0.000,0.000)s
PIN(60,15,0.000,0.000)g
PIN(80,5,0.030,0.070)d
LIG(60,15,70,15)
LIG(71,9,71,11)
LIG(71,12,71,14)
LIG(71,16,71,18)
LIG(71,19,71,21)
LIG(70,21,70,9)
LIG(72,21,72,9)
LIG(80,9,72,9)
LIG(80,5,80,9)
LIG(80,21,72,21)
LIG(80,25,80,21)
VLG  nmos nmos(drain,source,gate);
FSYM
FFIG C:\Documents and Settings\Administrator\My Documents\Dsch2\Book on CMOS\eeprom.sch
